# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-alpine

# Install build dependencies
RUN apk add --no-cache gcc musl-dev libffi-dev openssl-dev

# Set work directory and PYTHONPATH
env PYTHONUNBUFFERED=1
env PYTHONPATH=/app
WORKDIR /app

# Copy the utils and providers as top-level packages
COPY src/mcp_server_gusantong/utils /app/utils
COPY src/mcp_server_gusantong/providers /app/providers

# Copy project files
COPY pyproject.toml /app/
COPY src /app/src

# Install dependencies and the package
RUN pip install --no-cache-dir .

# Default entrypoint for stdio transport
ENTRYPOINT ["mcp-server-gusantong", "--transport", "stdio"]
